#!/usr/bin/env python
import optparse
import sys
import models
from collections import namedtuple

# Utilities borrowed from ./grade
def bitmap(sequence):
  """ Generate a coverage bitmap for a sequence of indexes """
  return reduce(lambda x,y: x|y, map(lambda i: long('1'+'0'*i,2), sequence), 0)

def bitmap2str(b, n, on='o', off='.'):
  """ Generate a length-n string representation of bitmap b """
  return '' if n==0 else (on if b&1==1 else off) + bitmap2str(b>>1, n-1, on, off)

def logadd10(x,y):
  """ Addition in logspace (base 10): if x=log(a) and y=log(b), returns log(a+b) """
  return x + math.log10(1 + pow(10,y-x))

optparser = optparse.OptionParser()
optparser.add_option("-i", "--input", dest="input", default="data/input", help="File containing sentences to translate (default=data/input)")
optparser.add_option("-t", "--translation-model", dest="tm", default="data/tm", help="File containing translation model (default=data/tm)")
optparser.add_option("-l", "--language-model", dest="lm", default="data/lm", help="File containing ARPA-format language model (default=data/lm)")
optparser.add_option("-n", "--num_sentences", dest="num_sents", default=sys.maxint, type="int", help="Number of sentences to decode (default=no limit)")
optparser.add_option("-k", "--translations-per-phrase", dest="k", default=1, type="int", help="Limit on number of translations to consider per phrase (default=1)")
optparser.add_option("-s", "--stack-size", dest="s", default=50, type="int", help="Maximum stack size (default=10)")
optparser.add_option("-v", "--verbose", dest="verbose", action="store_true", default=False,  help="Verbose mode (default=off)")
opts = optparser.parse_args()[0]

# TM contains tuples of words
tm = models.TM(opts.tm, opts.k)
lm = models.LM(opts.lm)
french = [tuple(line.strip().split()) for line in open(opts.input).readlines()[:opts.num_sents]]

def extract_english(h): 
  return "" if h.predecessor is None else "%s%s " % (extract_english(h.predecessor), h.phrase.english)

# tm should translate unknown words as-is with probability 1
for word in set(sum(french,())):
  if (word,) not in tm:
    tm[(word,)] = [models.phrase(word, 0.0)]

sys.stderr.write("Decoding %s...\n" % (opts.input,))
for french_sentence in french:
  # The following code implements a monotone decoding
  # algorithm (one that doesn't permute the target phrases).
  # Hence all hypotheses in stacks[i] represent translations of 
  # the first i words of the input sentence. You should generalize
  # this so that they can represent translations of *any* i words.
  
  # create named tuple so its easier to deal with the values we are working on
  hypothesis = namedtuple("hypothesis", "logprob, lm_state, predecessor, phrase, bitmap")
  initial_hypothesis = hypothesis(0.0, lm.begin(), None, None, 0)
  
  # initialize an array of dictionaries of size N+1 (where N is the number of tokens) 
  stacks = [{} for _ in french_sentence] + [{}]
  
  # add a sentence start token as the initial hypothesis to start with
  stacks[0][lm.begin()] = initial_hypothesis

  # loop through all but the last stack in the array of stacks (so for each word)
  for i, stack in enumerate(stacks[:-1]):
    
    # loop through stack dictionary contents, starting with the values with the lowest log probability
    for current_hypothesis in sorted(stack.itervalues(),key=lambda h: -h.logprob)[:opts.s]: # prune
      # loop over each word within the current range, that is (current-pos+1 -> length+1)
      for s in xrange(0, len(french_sentence)):
        for j in xrange(s + 1,len(french_sentence) + 1):
          wordspanbitmap = bitmap(range(s,j))
          if wordspanbitmap & current_hypothesis.bitmap != 0:
            # Bitmap collision
            continue
          elif not french_sentence[s:j] in tm:
            continue
          else:
            newbitmap = (current_hypothesis.bitmap | wordspanbitmap)
          for phrase in tm[french_sentence[s:j]]:
            logprob = current_hypothesis.logprob + phrase.logprob + 0.0 # TODO: Add the distance factor too
            current_lm_state = current_hypothesis.lm_state
            for word in phrase.english.split():
              (current_lm_state, word_logprob) = lm.score(current_lm_state, word)
              logprob += word_logprob
          
            logprob += lm.end(current_lm_state) if j == len(french_sentence) else 0.0
            new_hypothesis = hypothesis(logprob, current_lm_state, current_hypothesis, phrase, newbitmap)
            aligned_length = 0
            for c in bitmap2str(newbitmap, len(french_sentence)):
              if c == 'o':
                aligned_length += 1
            if current_lm_state not in stacks[aligned_length ] or stacks[aligned_length ][current_lm_state].logprob < logprob: # second case is recombination
              stacks[aligned_length ][current_lm_state] = new_hypothesis
  # take the lowest absolute log prob value as our winner
  winner = max(stacks[-1].itervalues(), key=lambda h: h.logprob)
  #print bitmap2str(winner.bitmap, len(french_sentence))
  #print len(bitmap2str(winner.bitmap, len(french_sentence)))
  print extract_english(winner)
  sys.stderr.write(extract_english(winner) + "\n");

  # such verbose
  if opts.verbose:
    def extract_tm_logprob(h):
      return 0.0 if h.predecessor is None else h.phrase.logprob + extract_tm_logprob(h.predecessor)
    tm_logprob = extract_tm_logprob(winner)
    sys.stderr.write("LM = %f, TM = %f, Total = %f\n" % 
      (winner.logprob - tm_logprob, tm_logprob, winner.logprob))
